### ISSUE TITLE
v0.1 Launch Gameplan

### ISSUE THREAD

**Issue by kremalicious** [bigchaindb/site#1]
I have a draft:
http://www.bigchain.io

Style wise, I extended the basic branding from the moodboard and created a system of colors, typography and components. There wasn't any indication of what hero image to use, thought going in a more spacy direction and "something is on the horizon" was fitting.

Considering the short timeframe, the very minimal concept and the fact the content won't be edited by multiple persons, I found using a huge CMS like WordPress is overkill right now and would just slow us down. So to use time most effectively for actual branding/design, I created the page with a static site generator, Jekyll. The catch: there's no admin interface except for editing markdown files on GitHub. On the upside: super fast site, way easier to maintain, makes creating new pages super quick. So I suggest keeping this system for the launch. If we decide we need a CMS later on, it can be converted into WP theme.
### Content

All content should be finalized in this Google Doc. I'll just transfer over the copy from there before launch:
https://docs.google.com/document/d/1dnIUOSBbDi34jS8XWFjIRnyQQ4NSHYYe3a65W--Vty4/edit?usp=sharing
### ToDo
- [x] decide on hero image
- [x] add benchmark diagram
- [x] finalize all copy
- [x] make form send stuff (MailChimp? Just email?) (#2)
- [x] create favicon & apple-touch-icon (6db5ce7fb03589892e790cdd983e8b3aab5631bb)
- [x] create sharing image (521f86cab8dc112d2a361accff62e9f2229bb98f)
- [x] add Google Analytics property ID
- [x] fix missing Fira woff2 (https://github.com/mozilla/Fira/pull/135)

bonus quest: add gulp deployment tasks
bonus quest: setup Codeship for build & deploy
