### ISSUE TITLE
Finding a UI for Jekyll

### ISSUE THREAD

**Issue by kremalicious** [bigchaindb/site#75]
_Goal: provide a basic visual workflow for editing copy including a preview of changes before they go live._

I came across https://forestry.io which looks nice & simple and seems perfect for our use case. Just creates form fields for all keys/values it can find in existing YAML frontmatter and handles images nicely with a drag & drop interface. Also handles all post types nicely so we could also use it for the new blog functionality. And it's free for up to 10 users.

forestry.io example:

<img width="797" alt="screen shot 2016-10-10 at 11 36 57" src="https://cloud.githubusercontent.com/assets/90316/19232072/f99654e4-8edd-11e6-9587-2ec4c51bf21f.png">

Body copy is still written in markdown but with nice highlighting:

<img width="531" alt="screen shot 2016-10-10 at 11 34 47" src="https://cloud.githubusercontent.com/assets/90316/19231996/933e6ff6-8edd-11e6-8725-c64ba05ef0ca.png">

@shemtovo could you please add `bigchain-website` to forestry.io, then add me as a Team member there?
### ToDo
- [x] add `bigchain-website` to Forestry.io
- [x] define and set file & image upload paths under site settings
- [x] get preview to work
- [x] test publishing workflow
  - [x] create a new page
  - [x] add text, add an image
  - [x] save & commit
  - [x] verify changes end up on live

Remaining thing is getting preview to work there which is a bit more tricky. The preview works but no styles/javascripts are loaded resulting in unstyled page.

All those »UI-on-top-of-jekyll« services depend on the standard Ruby-based Jekyll assets pipeline so in the end all those services just do a `jekyll serve` to show the preview. But this Jekyll assets pipeline has many limitations, which is why we use Gulp to handle the assets processing.

My strategy right now is to provide a basic set of styles in the standard `_saas` folder for Jekyll to process when doing a `jekyll serve`. It's fine when resulting css files are not super optimized as opposed to running through the Gulp-based build, it's just for preview purposes anyway.
### Alternatives
- [Siteleaf](https://www.siteleaf.com), is just weird, way too opinionated and they change almost all files upon first connection and in the end nothing worked in my tests
- [BowTie.io](https://bowtie.io), similar to Siteleaf with all its problems
- only locally: [jekyll-admin](https://github.com/jekyll/jekyll-admin), might have the same problem as forestry.io, fully depending on Jekyll assets pipeline
